name: Deploy MessageApp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to Docker hub
        run : echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build docker image
        run: docker build -t kautsarhasby/messaging-app:latest .
      - name: Push docker image to docker hub
        run: docker push kautsarhasby/messaging-app:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull kautsarhasby/messaging-app:latest
      - name: Delete old docker container
        run: docker rm -f messaging-app || true
      - name: Running new docker container
        run: |
          docker run -d \
            -p 8080:8080 -p 4000:4000 \
            --name messaging-app \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e APP_HOST=${{ secrets.APP_HOST }} \
            -e APP_PORT_SOCKET=${{ secrets.APP_PORT_SOCKET }} \
            -e APP_PORT=${{ secrets.APP_PORT }} \
            -e APP_NAME="${{ secrets.APP_NAME }}" \
            -e APP_SECRET=${{ secrets.APP_SECRET }} \
            -e MONGODB_URI=${{ secrets.MONGODB_URI }} \
            kautsarhasby/messaging-app:latest
